##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  archlinux:
    # Useful URL: https://git.archlinux.org/svntogit/community.git/tree/caja
    - autoconf-archive
    - clang
    - gcc
    - git
    - make
    - exempi
    - file
    - gobject-introspection
    - gvfs
    - intltool
    - libexif
    - libnotify
    - libsm
    - mate-common
    - mate-desktop
    - which
    - xorgproto

  debian:
    # Useful URL: https://github.com/mate-desktop/debian-packages
    # Useful URL: https://salsa.debian.org/debian-mate-team/caja
    - autopoint
    - clang
    - clang-tools
    - cppcheck
    - git
    - gobject-introspection
    - gtk-doc-tools
    - intltool
    - libdconf-dev
    - libexempi-dev
    - libexif-dev
    - libgail-3-dev
    - libgirepository1.0-dev
    - libglib2.0-dev
    - libgtk-3-dev
    - libgtk-layer-shell-dev
    - libmate-desktop-dev
    - libnotify-dev
    - libpango1.0-dev
    - libselinux1-dev
    - libstartup-notification0-dev
    - libx11-dev
    - libxml2-dev
    - mate-desktop
    - mate-common
    - python3-lxml
    - quilt
    - shared-mime-info
    - xvfb

  fedora:
    # Useful URL: https://src.fedoraproject.org/cgit/rpms/caja.git/
    - autoconf-archive
    - clang-analyzer
    - clang
    - cppcheck-htmlreport
    - git
    - gcc
    - gtk3-devel
    - gtk-layer-shell-devel
    - make
    - redhat-rpm-config
    - dbus-glib-devel
    - desktop-file-utils
    - exempi-devel
    - gobject-introspection-devel
    - cairo-gobject-devel
    - libexif-devel
    - libselinux-devel
    - libSM-devel
    - libxml2-devel
    - mate-common
    - mate-desktop-devel
    - pango-devel
    - python3-lxml
    - startup-notification-devel
    - libnotify-devel

  ubuntu:
    - autopoint
    - clang
    - clang-tools
    - git
    - gobject-introspection
    - gtk-doc-tools
    - intltool
    - libdconf-dev
    - libexempi-dev
    - libexif-dev
    - libgail-3-dev
    - libgirepository1.0-dev
    - libglib2.0-dev
    - libgtk-3-dev
    - libgtk-layer-shell-dev
    - libmate-desktop-dev
    - libnotify-dev
    - libpango1.0-dev
    - libselinux1-dev
    - libstartup-notification0-dev
    - libx11-dev
    - libxml2-dev
    - mate-common
    - python3-lxml
    - quilt
    - shared-mime-info

variables:
  - 'CHECKERS="
    -enable-checker deadcode.DeadStores
    -enable-checker alpha.deadcode.UnreachableCode
    -enable-checker alpha.core.CastSize
    -enable-checker alpha.core.CastToStruct
    -enable-checker alpha.core.IdenticalExpr
    -enable-checker alpha.core.SizeofPtr
    -enable-checker alpha.security.ArrayBoundV2
    -enable-checker alpha.security.MallocOverflow
    -enable-checker alpha.security.ReturnPtrRange
    -enable-checker alpha.unix.SimpleStream
    -enable-checker alpha.unix.cstring.BufferOverlap
    -enable-checker alpha.unix.cstring.NotNullTerminated
    -enable-checker alpha.unix.cstring.OutOfBounds
    -enable-checker alpha.core.FixedAddr
    -enable-checker security.insecureAPI.strcpy"'

before_scripts:
  - if [ ${DISTRO_NAME} == "debian" ];then
  -     egrep -lRZ 'G_GNUC_BEGIN_IGNORE_DEPRECATIONS' . | xargs -0 -l sed -i -e 's/G_GNUC_BEGIN_IGNORE_DEPRECATIONS/ /g'
  -     egrep -lRZ 'G_GNUC_END_IGNORE_DEPRECATIONS' . | xargs -0 -l sed -i -e 's/G_GNUC_END_IGNORE_DEPRECATIONS/ /g'
  - fi
  - curl -Ls -o /usr/bin/gla11y https://github.com/hypra/gla11y/raw/v0.3/gla11y
  - chmod +x /usr/bin/gla11y

build_scripts:
  - if [ ${DISTRO_NAME} == "debian" ];then
  -     export CFLAGS+=" -Wsign-compare -Wunused-macros"
  -     cppcheck --enable=warning,style,performance,portability,information,missingInclude .
  - fi

  - NOCONFIGURE=1 ./autogen.sh
  - scan-build $CHECKERS ./configure --enable-empty-view --enable-compile-warnings=maximum 
  - if [ $CPU_COUNT -gt 1 ]; then
  -     if [ ${DISTRO_NAME} == "debian" ];then
  -         scan-build $CHECKERS --keep-cc --use-cc=clang --use-c++=clang++ -o html-report make -j $(( CPU_COUNT + 1 ))
  -         make clean
  -     fi
  -     scan-build $CHECKERS --keep-cc -o html-report make -j $(( CPU_COUNT + 1 ))
  - else
  -     if [ ${DISTRO_NAME} == "debian" ];then
  -         scan-build $CHECKERS --keep-cc --use-cc=clang --use-c++=clang++ -o html-report make
  -         make clean
  -     fi
  -     scan-build $CHECKERS --keep-cc -o html-report make
  - fi

after_scripts:
  - if [ ${DISTRO_NAME} == "fedora" ];then
  -   cppcheck --xml --output-file=cppcheck.xml --enable=warning,style,performance,portability,information,missingInclude .
  -   cppcheck-htmlreport --title=${REPO_NAME} --file=cppcheck.xml --report-dir=cppcheck-htmlreport
  -   ./gen-index -l 20 -i https://github.com/${OWNER_NAME}/mate-icon-theme/raw/master/mate/16x16/apps/system-file-manager.png
  - fi
  - if [ ${DISTRO_NAME} == "debian" ];then
  -     make install
  -     if xvfb-run make check; then :; else cat eel/test-suite.log; cat src/test-suite.log; false; fi
  - fi
  - make distcheck

releases:
  draft: false
  prerelease: false
  checksum: true
  file_glob: true
  files: caja-*.tar.xz
  github_release:
    tags: true
    overwrite: true
    base_version: 1.20.0
    notify_servers:
      - https://release.mate-desktop.org/release
