.\" Man page for caja-file-management-properties
.TH CAJA-FILE-MANAGEMENT-PROPERTIES 1 "29 January 2014" "MATE Desktop Environment" "General Manual"
.\" Please adjust this date whenever revising the manpage.
.\"
.SH "NAME"
Caja\-file\-management\-properties \- Caja File Management Preferences
.SH "SYNOPSIS"
.B caja\-file\-management\-properties
.SH "DESCRIPTION"
Caja File Management Properties is distributed as a part of the caja package and is used to configure Caja's preferences. It is typically accessible through the "Edit" menu in Caja browser windows, or by pressing "ALT+E" and then "N" once the menu opens.
.PP
File Management Preferences allows the user to configure the way caja behaves.
.PP
You can specify appearance preferences for the Default View; and defaults for Icon, Compact, List, and Tree View; and select sort options and display options. You can configure Caja to recognize Single or Double Click input; as well as Include a Delete command and menu option that bypasses the Trash. Caja File Management Preferences (\fBcaja-file-management-properties\fR) also allows you to tell Caja how to handle certain files; whether to View or Run executable text files; Automatically view or play Media like CDs, DVDs, or photos, and which applications to use when performing these tasks. Among some other options, this dialog also allows you to adjust file-preview settings, and settings for installed plugins if they exist.
.SH "BUGS"
.SS Should you encounter any bugs, they may be reported at: 
https://github.com/mate-desktop/caja/issues
.SH "AUTHORS"
.SS This Man Page has been written for the MATE Desktop Environment by:
Adam Erdman <hekel@archlinux.info> (2014)
.SH "SEE ALSO"
.SS
Caja documentation can be found from the "Help" menu, or by pressing the F1 key. 
Further information may also be available at: https://wiki.mate-desktop.org/docs
.P
.BR "caja" (1),
.BR "caja-autorun-software" (1),
.BR "caja-connect-server" (1)
