.\" Man page for caja-connect-server
.TH CAJA-CONNECT-SERVER 1 "29 January 2014" "MATE Desktop Environment" "General Manual"
.\" Please adjust this date whenever revising the manpage.
.\"
.SH "NAME"
Caja\-connect\-server \- Connect to Server dialog for Caja
.SH "SYNOPSIS"
.B caja\-connect\-server [OPTIONS]
.SH "DESCRIPTION"
Caja Connect Server is the connection manager for Caja/MATE. It is provided as a part of the Caja package for the MATE Desktop Environment.
.PP
Simply running "\fBcaja\-connection\-server\fR" will open a simple dialog allowing you to select the server type, and specify the server address, port, and login credentials for the server you want to connect to. This is the same dialog accessible via the Caja "File" menu, and the MATE Desktop "Places" menu.
.PP
You can use the Caja file manager to access remote servers such as SSH, FTP, and WebDav (HTTP/HTTPS) Servers.
.PP
If you desire to mount and access remote servers via console commands, you should use \fBcaja\fR directly. See: \fBcaja\fR(1)
.SH "OPTIONS"
.TP
\fB\-\-display=DISPLAY\fR
X display to use.
.TP
\fB\-?, \-h, \-\-help\fR
Print standard command line options.
.TP
\fB\-\-help\-all\fR
Print all command line options.
.SH "BUGS"
.SS Should you encounter any bugs, they may be reported at: 
https://github.com/mate-desktop/caja/issues
.SH "AUTHORS"
.SS This Man Page has been written for the MATE Desktop Environment by:
Adam Erdman <hekel@archlinux.info> (2014)
.SH "SEE ALSO"
.SS
Caja documentation can be found from the "Help" menu, or by pressing the F1 key. 
Further information may also be available at: https://wiki.mate-desktop.org/docs
.P
.BR "caja" (1),
.BR "caja-autorun-software" (1),
.BR "caja-file-management-properties" (1)
