.IX Title "caja-autorun-software 1"
.TH caja-autorun-software 1 "26 Sep 2013"
.SH "NAME"
caja\-autorun\-software
.SH "SYNOPSIS"
.IX Header "SYNOPSIS"
This executable is part of the package 'caja': The \s-1MATE\s0 Desktop File Manager
.SH "DESCRIPTION"
.IX Header "DESCRIPTION"
This package contains Caja, the file manager for the \s-1MATE\s0
Desktop Environment.
.SH "LICENSE"
.IX Header "LICENSE"
\&\s-1GPL\s0 v2 or later
